set(CPACK_PACKAGE_VERSION_MAJOR ${exportpred_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${exportpred_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${exportpred_VERSION_PATCH})

SET(CPACK_GENERATOR "STGZ;TGZ")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Exportpred predicts protein export via the PEXEL pathway in Plasmodium.")
SET(CPACK_PACKAGE_NAME "exportpred")
SET(CPACK_PACKAGE_VENDOR "WEHI")
SET(CPACK_RESOURCE_FILE_LICENSE "${exportpred_SOURCE_DIR}/COPYING.txt")
SET(CPACK_RESOURCE_FILE_README "${exportpred_SOURCE_DIR}/README.txt")
SET(CPACK_SOURCE_PACKAGE_FILE_NAME "exportpred-${EXPORTPRED_VERSION}")
SET(CPACK_SOURCE_GENERATOR "TGZ")

include(CPack)
